zia/services/security_policy_settings/security_policy_settings.go
zia/services/security_policy_settings/service.go
zia/services/user_authentication_settings/service.go
zia/services/user_authentication_settings/user_authentication_settings.go

This PR adds missing zia resources `security policy settings`  & `user authentication settings`

add missing zia resources

---

.github/workflows/test.yml
zpa/client_test.go
zpa/config.go

Fix: zpa config.go cloud identification

Fix: zpa config.go cloud identification

---

zpa/client_test.go
zpa/config.go

feat: Added support to preview cloud

feat: Added support to preview cloud

---

zia/services/usermanagement/users.go

Fix: Group ID List Assignment for User Accounts

Fix: Group ID List Assignment for User Accounts

---

zpa/services/appconnectorgroup/zpa_app_connector_group.go

feat(new parameters):App Connector Group TCPQuick*

feat(new parameters):App Connector Group TCPQuick*

---

zia/services/trafficforwarding/gretunnels/gretunnels.go

Added new zia parameters

---

zpa/services/applicationsegment/zpa_application_segment.go
zpa/services/applicationsegmentinspection/zpa_application_segment_inspection.go
zpa/services/applicationsegmentpra/zpa_application_segment_pra.go
zpa/services/browseraccess/zpa_browser_access.go
zpa/services/common/common.go

This PR filters application segments apps in GetAll api calls depending on the resource type (PRA, Browser access, Inspection).

filter application segment in GetAll call

---

zpa/services/applicationsegmentpra/zpa_application_segment_pra.go
zpa/services/browseraccess/zpa_browser_access.go

(fix) Missing parameters for application segments

(fix) Missing parameters for application segments

---

zpa/services/serviceedgecontroller/zpa_service_edge_controller.go

feat: Implemented bulk delete of service_edge_controller

feat: Implemented bulk delete of service_edge_controller

---

zpa/services/bacertificate/zpa_ba_certificate.go

Added certblob parameter to zpa_ba_certificate

Added certblob parameter to zpa_ba_certificate

---

zia/services/adminuserrolemgmt/adminroles.go
zia/services/common/common.go
zia/services/dlpdictionaries/dlpdictionaries.go
zia/services/eventlogentryreport/eventlogentryreport.go
zia/services/eventlogentryreport/service.go
zia/services/intermediatecacertificates/intermediatecacertificates.go
zia/services/locationmanagement/locationmanagement.go
zia/services/urlcategories/urlcategories.go

Added new ZIA API parameters to SDK

Added new ZIA API parameters to SDK

---

zia/services/common/common.go

Fix: ZIA Data Source Pagination Issue

Fix: ZIA Data Source Pagination Issue

---

zia/services/urlcategories/urlcategories.go

new zia url category parameters

new zia url category parameters

---

.pre-commit-config.yaml
CHANGELOG.md
zia/services/urlfilteringpolicies/urlfilteringpolicies.go

Added ``deviceTrustLevels`` parameters to zia

Added ``deviceTrustLevels`` parameters to zia

---

zia/services/urlfilteringpolicies/urlfilteringpolicies.go

Added omitempty to bool parameters in urlfiltering

---

zia/services/firewallpolicies/filteringrules/filteringrules.go

Added omitempty to filteringrule fulllogging

---

CHANGELOG.md
zpa/services/inspectioncontrol/inspection_custom_controls/zpa_inspection_custom_controls.go
zpa/services/inspectioncontrol/inspection_predefined_controls/zpa_inspection_predefined-controls.go
zpa/services/inspectioncontrol/inspection_profile/zpa_inspection_profile.go

Added New ZPA Inspection Control Parameters

---

zia/services/firewallpolicies/filteringrules/filteringrules.go

Fix FW Enable Full Logging

---

CHANGELOG.md
zia/services/dlp_engines/dlp_engines.go
zia/services/dlp_icap_servers/dlp_icap_server.go
zia/services/dlp_icap_servers/service.go
zia/services/dlp_idm_profiles/dlp_idm_profiles.go
zia/services/dlp_idm_profiles/service.go
zia/services/dlp_incident_receiver_servers/dlp_incident_receiver_servers.go
zia/services/dlp_incident_receiver_servers/service.go
zia/services/dlp_notification_templates/dlp_notification_templates.go
zia/services/dlp_web_rules/dlp_web_rules.go

Added new zia dlp endpoints

---

zia/services/dlp_web_rules/dlp_web_rules.go

Fix zia dlp_web_rules

---

.pre-commit-config.yaml
zia/services/firewallpolicies/applicationservices/applicationservices.go
zia/services/firewallpolicies/applicationservices/service.go
zia/services/firewallpolicies/applicationservicesgroup/applicationservicesgroup.go
zia/services/firewallpolicies/applicationservicesgroup/service.go

(feat) New zia application services group endpoint

---

zia/services/adminuserrolemgmt/adminroles.go
zia/services/adminuserrolemgmt/adminusers.go
zia/services/devicegroups/devicegroups.go
zia/services/dlpdictionaries/dlpdictionaries.go
zia/services/eventlogentryreport/eventlogentryreport.go
zia/services/firewallpolicies/filteringrules/filteringrules.go
zia/services/firewallpolicies/ipdestinationgroups/ipdestinationgroups.go
zia/services/firewallpolicies/ipsourcegroups/ipsourcegroups.go
zia/services/intermediatecacertificates/intermediatecacertificates.go
zia/services/locationmanagement/locationgroups/locationgroups.go
zia/services/locationmanagement/locationmanagement.go
zia/services/rule_labels/rule_labels.go
zia/services/security_policy_settings/security_policy_settings.go
zia/services/trafficforwarding/greinternalipranges/greinternalipranges.go
zia/services/trafficforwarding/gretunnelinfo/gretunnelinfo.go
zia/services/trafficforwarding/gretunnels/gretunnels.go
zia/services/trafficforwarding/staticips/staticips.go
zia/services/trafficforwarding/virtualipaddresslist/virtualipaddresslist.go
zia/services/trafficforwarding/vpncredentials/vpncredentials.go
zia/services/urlcategories/urlcategories.go
zia/services/urlfilteringpolicies/urlfilteringpolicies.go
zia/services/user_authentication_settings/user_authentication_settings.go
zia/services/usermanagement/department.go
zia/services/usermanagement/group.go
zia/services/usermanagement/users.go

(doc) Added comments to all struct attributes

(doc) Added comments to all struct attributes

---

examples/zdx/reports/devices/README.md
examples/zdx/reports/users/README.md
zdx/services/reports/applications/application_score_metrics.go
zdx/services/reports/applications/applications.go

Added zdx program examples

---

CHANGELOG.md
zpa/services/applicationsegment/zpa_application_segment.go
zpa/services/applicationsegmentinspection/zpa_application_segment_inspection.go
zpa/services/applicationsegmentpra/zpa_application_segment_pra.go
zpa/services/browseraccess/zpa_browser_access.go

Added missing app segment attributes

Added missing app segment attributes

---

zpa/services/clienttypes/clienttypes.go
zpa/services/clienttypes/service.go
zpa/services/platforms/platforms.go
zpa/services/platforms/service.go

(feat) New zpa platform and clienttype endpoints

(feat) New zpa platform and clienttype endpoints

---

CHANGELOG.md
zia/services/locationmanagement/locationmanagement.go

(fix) Added new Auth Attribs to zia Location Mgmt

(fix) Added new Auth Attribs to zia Location Mgmt

---

CHANGELOG.md
zpa/services/idpcontroller/zpa_idp_controller.go

[fix] fix: ZPA IDP Controller New Attributes

[fix] fix: ZPA IDP Controller New Attributes

---

zpa/client.go

Reverts zscaler/zscaler-sdk-go#89

Revert "[FIX] refresh expired token &  reduce number of items per page to avoid exceeding max response size"

---

zpa/client.go

merge PRs #90 and #91

---

zia/services/locationmanagement/locationmanagement.go

(feat) Add support to sublocation search function

(feat) Add support to sublocation search function

---

zia/services/trafficforwarding/gretunnels/gretunnels.go
zia/services/trafficforwarding/virtualipaddresslist/virtualipaddresslist.go

Make WithinCountry a pointer for GRE Tunnel response
City, Region, Latitude & Longitude to VIP response
Implement get all by source IP & get all VIPs by all existing source IPs

add more fields and methods

---

CHANGELOG.md
zia/services/dlp_engines/dlp_engines.go

Get predefined engines by name and set name to predefinedEngineName

get predefined engines by name and set name

---

zpa/config.go

Retry on  errors:  `non.restricted.entity.authorization.failed` & `bad.request`

retry on some bad-request errors

---

CHANGELOG.md
zia/services/dlp_idm_profiles/dlp_idm_profiles.go
zia/services/dlp_idm_profiles/dlp_idm_profiles_lite.go

(feat) Added DLP IDM Profile Lite Schema

(feat) Added DLP IDM Profile Lite Schema

---

CHANGELOG.md

(feat) ZIA add auditor user search attribute

(feat) ZIA add auditor user search attribute

---

CHANGELOG.md
zia/services/dlpdictionaries/dlpdictionaries.go

(feat) Added new ZIA DLP Dictionary Attributes

(feat) Added new ZIA DLP Dictionary Attributes

---

CHANGELOG.md
zpa/services/inspectioncontrol/inspection_profile/zpa_inspection_profile.go

(feat) ZPA New Inspection Profile Attributes

(feat) ZPA New Inspection Profile Attributes

---

CHANGELOG.md
zpa/services/clienttypes/clienttypes.go

(Fix) Added new ZPA Client Type ``zapp_partner``

(Fix) Added new ZPA Client Type ``zapp_partner``

---

CHANGELOG.md
zia/services/dlp_exact_data_match/dlp_edm_schemas_lite.go
zia/services/dlp_exact_data_match/dlp_exact_data_match.go
zia/services/dlp_exact_data_match/service.go

(feat) Added ZIA DLP Exact Data Match Schema

(feat) Added ZIA DLP Exact Data Match Schema

---

CHANGELOG.md
zpa/config.go

(Fix) ZPA API Client New Exception Handling

(Fix) ZPA API Client New Exception Handling

---

CHANGELOG.md
zpa/services/appconnectorgroup/zpa_app_connector_group.go

feat: Added new attribute waf_disabled to zpa_app_connector_group

feat: Added new attribute waf_disabled to zpa_app_connector_group

---

.github/workflows/ci.yml
.github/workflows/reuse-zdx-tests.yml
.github/workflows/reuse-zia-tests.yml
.github/workflows/test.yml
tests/integration/zpa/zpa_policy_access_rule1_test.go
tests/integration/zpa/zpa_policy_access_rule2_test.go
tests/integration/zpa/zpa_policy_access_rule3_test.go
zpa/client_test.go

feat: Added new access policy tests

feat: Added new access policy tests

---

CHANGELOG.md
zpa/services/scimattributeheader/zpa_scim_attribute_header.go

fix: Fixed SCIM attribute filter email value

fix: Fixed SCIM attribute filter email value

---

CHANGELOG.md
zpa/client_test.go
zpa/config.go

feat: Added support to ZPA GOV US Cloud

feat: Added support to ZPA GOV US Cloud

---

.github/workflows/reuse-zpa-tests.yml
.github/workflows/test.yml
zpa/client_test.go
zpa/config.go
zpa/services/cloudbrowserisolation/isolationprofile/zpa_isolation_profile_test.go
zpa/services/policysetcontroller/zpa_policy_access_isolation_rule_test.go

feat: Added support to QA2 Cloud - 07-25-2023

feat: Added support to QA2 Cloud

---

.pre-commit-config.yaml
CHANGELOG.md
README.md
cache/cache.go
cache/go-cache.go
cache/nop-cache.go
go.mod
go.sum
logger/logger.go
zpa/client.go
zpa/config.go
zpa/errors.go

fix: Added HTTP optimization to zpa api client

fix: Added HTTP optimization to zpa api client

---

zpa/services/machinegroup/zpa_machine_group.go

Fix: Fixed MicrotenantID search for Machine Group

Fix: Fixed MicrotenantID search for Machine Group

---

CHANGELOG.md
zpa/services/provisioningkey/zpa_provisioning_key.go

feat: Added microtenant support to zpa provisioning key

feat: Added microtenant support to zpa provisioning key

---

cache/cache.go
cache/go-cache.go
cache/nop-cache.go
ratelimiter/limiter.go
zia/client.go
zia/config.go
zpa/config.go

feat: Added zia client ratelimiter and cache functionality

feat: Added zia client ratelimiter and cache functionality

---

CHANGELOG.md
docs/guides/release-notes.md
zpa/services/lssconfigcontroller/zpa_lss_config_controller.go

feat: Added ZPA LSS Config Controller

feat: Added ZPA LSS Config Controller

---

CHANGELOG.md
docs/guides/release-notes.md
zpa/services/common/common.go

fix: Fixed zpa custom pagination search mechanism

fix: Fixed zpa custom pagination search mechanism

---

CHANGELOG.md
docs/guides/release-notes.md
zpa/services/applicationsegmentinspection/zpa_application_segment_inspection.go
zpa/services/applicationsegmentpra/zpa_application_segment_pra.go

(fix): Fixed application segment pra and inspection

(fix): Fixed application segment pra and inspection

---

CHANGELOG.md
docs/guides/release-notes.md
zia/services/locationmanagement/locationmanagement.go

feat: Added ZIA GetAllSublocations function

feat: Added ZIA GetAllSublocations function

---

.github/workflows/test.yml
CHANGELOG.md
docs/guides/release-notes.md
tests/testCommon.go
zpa/services/cloudbrowserisolation/cbibannercontroller/cbibannercontroller_test.go
zpa/services/cloudbrowserisolation/cbiprofilecontroller/cbiprofilecontroller_test.go
zpa/services/microtenants/microtenants_test.go

(fix): ZPA Disabled CBI Edge Test Cases

(fix): ZPA Disabled CBI Edge Test Cases

---

CHANGELOG.md
Makefile
docs/guides/release-notes.md
zpa/services/enrollmentcert/service.go
zpa/services/enrollmentcert/zpa_enrollmentcert.go

(Fix) Added missing microtenant_id attribute to zpa enrollment cert

(Fix) Added missing microtenant_id attribute to zpa enrollment cert

---

.github/workflows/test.yml
CHANGELOG.md
docs/guides/release-notes.md
zpa/services/common/common.go
zpa/services/scimgroup/service.go
zpa/services/scimgroup/zpa_scim_group.go
zpa/services/scimgroup/zpa_scim_group_test.go

feat: Implemented SCIM Group SortOrder and SortBy Options

feat: Implemented SCIM Group SortOrder and SortBy Options

---

.pre-commit-config.yaml
zia/services/sandbox/sandbox_settings/sandbox_settings.go
zia/services/sandbox/sandbox_settings/sandbox_settings_test.go
zia/services/sandbox/sandbox_settings/service.go
zia/services/sandbox/sandbox_submission/sandbox_submission.go
zia/services/sandbox/sandbox_submission/sandbox_submission_test.go
zia/services/sandbox/sandbox_submission/service.go

feat: Added Sandbox Endpoint Resources

feat: Added Sandbox Endpoint Resources

---

zpa/services/bacertificate/service.go
zpa/services/bacertificate/zpa_ba_certificate.go
zpa/services/bacertificate/zpa_ba_certificate_test.go
zpa/services/browseraccess/zpa_browser_access_test.go
zpa/services/policysetcontroller/zpa_policy_access_rule_test.go

feat: Added zpa application segment browser access test

feat: Added zpa application segment browser access test

---

zia/services/devicegroups/devicegroups.go
zia/services/devicegroups/devicegroups_test.go
zia/services/dlp/dlp_exact_data_match/dlp_exact_data_match.go
zia/services/dlp/dlp_exact_data_match/dlp_exact_data_match_test.go
zia/services/dlp/dlp_exact_data_match_lite/dlp_exact_data_match_lite.go
zia/services/dlp/dlp_exact_data_match_lite/dlp_exact_data_match_lite_test.go
zia/services/dlp/dlp_exact_data_match_lite/service.go
zia/services/dlp/dlp_idm_profiles/dlp_idm_profiles.go
zia/services/dlp/dlp_idm_profiles/dlp_idm_profiles_test.go
zia/services/dlp/dlp_idm_profiles_lite/dlp_idm_profiles_lite.go
zia/services/dlp/dlp_idm_profiles_lite/dlp_idm_profiles_lite_test.go
zia/services/dlp/dlp_idm_profiles_lite/service.go
zia/services/sandbox/sandbox_submission/sandbox_submission_test.go

(feat): Added more dlp integration test cases

(feat): Added more dlp integration test cases

---

zpa/services/appconnectorgroup/zpa_app_connector_group_test.go
zpa/services/cloudbrowserisolation/cbicertificatecontroller/cbicertificatecontroller_test.go
zpa/services/cloudbrowserisolation/cbiregions/cbiregions_test.go
zpa/services/cloudbrowserisolation/cbizpaprofile/cbizpaprofile_test.go
zpa/services/cloudbrowserisolation/isolationprofile/zpa_isolation_profile_test.go
zpa/services/customerversionprofile/zpa_customer_version_profile_test.go
zpa/services/enrollmentcert/zpa_enrollmentcert_test.go
zpa/services/idpcontroller/zpa_idp_controller_test.go
zpa/services/machinegroup/zpa_machine_group_test.go
zpa/services/postureprofile/zpa_posture_profile_test.go
zpa/services/trustednetwork/zpa_trusted_network_test.go

feat: Added more zpa integration test cases

feat: Added more zpa integration test cases

---

.github/workflows/release.yml
CHANGELOG.md
docs/guides/release-notes.md
zia/services/dlp/dlp_web_rules/dlp_web_rules.go
zia/services/dlp/dlp_web_rules/dlp_web_rules_test.go
zpa/services/postureprofile/zpa_posture_profile_test.go

fix: Added new ZIA Web DLP Rule attributes

fix: Added new ZIA Web DLP Rule attributes

---

CHANGELOG.md
docs/guides/release-notes.md
zia/services/dlp/dlp_engines/dlp_engine_lite_test.go
zia/services/dlp/dlp_engines/dlp_engines.go
zia/services/dlp/dlp_web_rules/dlp_web_rules.go
zia/services/dlp/dlp_web_rules/dlp_web_rules_test.go

(fix): Added missing dlp engine and web dlp rule attributes

(fix): Added missing dlp engine and web dlp rule attributes

---

CHANGELOG.md
docs/guides/release-notes.md
zia/services/firewallpolicies/filteringrules/firewall_filtering_rule_test.go
zia/services/urlfilteringpolicies/url_filtering_rules_test.go
zia/services/urlfilteringpolicies/urlfilteringpolicies.go

(feat): Added ZIA URL Filtering Rule CBI Profile Support

(feat): Added ZIA URL Filtering Rule CBI Profile Support

---

.github/workflows/reuse-zcon-tests.yml
.github/workflows/reuse-zia-tests.yml
zia/services/firewallpolicies/networkservicegroups/networkservicegroups_test.go
zia/services/firewallpolicies/networkservices/networkservices_test.go

feat: Added Network Services Group Test

feat: Added Network Services Group Test

---

.github/dependabot.yml
CHANGELOG.md
docs/guides/release-notes.md
zia/services/dlp/dlp_web_rules/dlp_web_rules.go
zia/services/dlp/dlp_web_rules/dlp_web_rules_test.go
zia/services/firewallpolicies/filteringrules/filteringrules.go
zia/services/sandbox/sandbox_report/sandbox_report_test.go
zia/services/urlfilteringpolicies/urlfilteringpolicies.go
zpa/services/applicationsegment/zpa_application_segment.go
zpa/services/applicationsegment/zpa_application_segment_test.go
zpa/services/common/common.go
zpa/services/postureprofile/zpa_posture_profile.go
zpa/services/serviceedgegroup/zpa_service_edge_group.go

[FIX]: Added new ZPA Attributes

[FIX]: Added new ZPA Attributes

---

CHANGELOG.md
docs/guides/release-notes.md
zia/services/dlp/dlp_web_rules/dlp_web_rules.go
zia/services/dlp/dlp_web_rules/dlp_web_rules_test.go
zia/services/firewallpolicies/filteringrules/filteringrules.go
zia/services/firewallpolicies/filteringrules/firewall_filtering_rule_test.go
zia/services/urlfilteringpolicies/url_filtering_rules_test.go
zia/services/urlfilteringpolicies/urlfilteringpolicies.go

fix: Fixed workloadGroups attribute for several resources

fix: Fixed workloadGroups attribute for several resources

---

.github/workflows/zcon-test.yml
.github/workflows/zdx-test.yml
.github/workflows/zia-test.yml
.github/workflows/zpa-test.yml
Makefile
zcon/services/ecgroup/ecgroup_test.go
zcon/services/locationmanagement/location/location_test.go
zia/services/dlp/dlp_engines/dlp_engines_test.go
zia/services/sandbox/sandbox_submission/sandbox_submission_test.go
zia/services/trafficforwarding/virtualipaddress/virtualipaddress_test.go
zia/services/workloadgroups/workloadgroups_test.go
zpa/services/cloudbrowserisolation/cbibannercontroller/cbibannercontroller_test.go
zpa/services/microtenants/microtenants_test.go
zpa/services/scimattributeheader/zpa_scim_attribute_header_test.go
zpa/services/trustednetwork/zpa_trusted_network_test.go

gh: Refactor Github Action Workflow

gh: Refactor Github Action Workflow

---

.github/workflows/zia-test.yml
zia/services/forwarding_control_policy/forwarding_rules/forwarding_rules_test.go
zia/services/forwarding_control_policy/zpa_gateways/zpa_gateways_test.go
zia/services/workloadgroups/workloadgroups_test.go

gh: Refactor github actions

---

CHANGELOG.md
docs/guides/release-notes.md
zpa/services/browseraccess/zpa_browser_access_test.go
zpa/services/policysetcontroller/policysetcontroller.go
zpa/services/scimattributeheader/zpa_scim_attribute_header_test.go
zpa/services/scimgroup/zpa_scim_group_test.go
zpa/services/serviceedgegroup/zpa_service_edge_group.go

feat: Added support to zpa policy access redirection

feat: Added support to zpa policy access redirection

---

CHANGELOG.md
docs/guides/release-notes.md
zia/config.go

(fix): Fixed ZIA JsessionID refresh logic

---

CHANGELOG.md
docs/guides/release-notes.md
zpa/services/applicationsegmentpra/zpa_application_segment_pra.go

(fix): Fixed ZPA Application Segment PRA changed attribute change from sraPortal to praApps

---

CHANGELOG.md
docs/guides/release-notes.md
zpa/services/policysetcontrollerv2/policysetcontrollerv2.go

(Fix): Fixed ConvertV1ResponseToV2Request Missing ObjectType

---

CHANGELOG.md
docs/guides/release-notes.md
docs/guides/support.md
zia/services/trafficforwarding/vpncredentials/vpncredentials.go

Fix: Added GetByIP Function to vpncredentials model

---

CHANGELOG.md
docs/guides/release-notes.md
zia/services/common/common.go
zia/services/dlp/dlp_web_rules/dlp_web_rules.go
zia/services/dlp/dlp_web_rules/dlp_web_rules_test.go

fix: Fixed dlp web rule attributes

---

CHANGELOG.md
docs/guides/release-notes.md
zia/sweep/main_test.go
zpa/services/bacertificate/zpa_ba_certificate.go

Fix: Fixed ZPA BA Certificate missing attribute

---

CHANGELOG.md
docs/guides/release-notes.md
zia/config.go

fix: Added ZIA Auth custom error handling

---

CHANGELOG.md
docs/guides/release-notes.md
zia/services/urlfilteringpolicies/urlfilteringpolicies.go

fix: Added missing sourceIPGroups attributes to ZIA package

---

CHANGELOG.md
docs/guides/release-notes.md
zia/sweep/main_test.go
zpa/services/applicationsegmentbytype/applicationsegmentbytype.go
zpa/services/applicationsegmentbytype/applicationsegmentbytype_test.go
zpa/services/applicationsegmentbytype/service.go
zpa/services/applicationsegmentinspection/zpa_application_segment_inspection.go
zpa/services/applicationsegmentinspection/zpa_application_segment_inspection_test.go
zpa/services/applicationsegmentpra/zpa_application_segment_pra.go
zpa/services/applicationsegmentpra/zpa_application_segment_pra_test.go
zpa/services/browseraccess/zpa_browser_access.go
zpa/services/browseraccess/zpa_browser_access_test.go
zpa/services/serviceedgegroup/zpa_service_edge_group_test.go
zpacoverage.html

fix: Fixed ZPA getAppsByType package

---

.github/workflows/zpa-test.yml
CHANGELOG.md
docs/guides/release-notes.md
zia/client_test.go
zia/config.go
zia/services/urlfilteringpolicies/url_filtering_rules_test.go
ziacoverage.html

fix: Fixed ZIA API Client Session Refresh Handling

---

CHANGELOG.md
docs/guides/release-notes.md
zpa/services/applicationsegmentinspection/zpa_application_segment_inspection.go
zpa/services/applicationsegmentpra/zpa_application_segment_pra.go
zpa/services/policysetcontroller/policysetcontroller.go
zpa/services/policysetcontrollerv2/policysetcontrollerv2.go

fix: Enhanced filtering capabilities for ZPA app segment pra

---

.github/workflows/zcc-test.yml
.github/workflows/zcon-test.yml
.github/workflows/zdx-test.yml
.github/workflows/zia-test.yml
.github/workflows/zpa-test.yml
CHANGELOG.md
docs/guides/release-notes.md
examples/zdx/alerts/go.mod
examples/zdx/alerts/go.sum
go.mod
zdx/services/administration/administration.go
zdx/services/common/common.go
zdx/services/reports/users/types.go
zia/client.go
zia/config.go
zpa/services/applicationsegment_move/applicationsegment_move_test.go
zpa/services/applicationsegment_share/applicationsegment_share_test.go
zpa/services/applicationsegmentbytype/applicationsegmentbytype_test.go
zpa/services/browseraccess/zpa_browser_access_test.go
zpa/sweep/main_test.go

Fix: Added New ZIA API Client Time Ticker to Manage Session Renewal

---

CHANGELOG.md
docs/guides/release-notes.md
zpa/services/cloudbrowserisolation/cbiprofilecontroller/cbiprofilecontroller.go
zpa/services/policysetcontrollerv2/policysetcontrollerv2.go

Fix: Fixed ZPA Policy Set Controller omitempty tags for slice attributes

---

CHANGELOG.md
docs/guides/release-notes.md
zpa/services/cloudbrowserisolation/cbiprofilecontroller/cbiprofilecontroller.go

fix: Fixed ZPA CBI Profile Controllert Attributes

---

.github/workflows/zdx-test.yml
CHANGELOG.md
docs/guides/release-notes.md
zdx/services/alerts/alerts_test.go
zia/services/location/locationmanagement/locationmanagement.go

fix: Fixed Location Management Missing Attributes

---

CHANGELOG.md
docs/guides/release-notes.md
zpa/services/cloudbrowserisolation/cbibannercontroller/cbibannercontroller.go
zpa/services/cloudbrowserisolation/cbibannercontroller/cbibannercontroller_test.go
zpa/services/cloudbrowserisolation/cbicertificatecontroller/cbicertificatecontroller.go
zpa/services/cloudbrowserisolation/cbicertificatecontroller/cbicertificatecontroller_test.go
zpa/services/cloudbrowserisolation/cbiprofilecontroller/cbiprofilecontroller.go
zpa/services/cloudbrowserisolation/cbiprofilecontroller/cbiprofilecontroller_test.go
zpa/services/cloudbrowserisolation/cbizpaprofile/cbizpaprofile.go
zpa/services/cloudbrowserisolation/cbizpaprofile/cbizpaprofile_test.go

fix: Fixed Cloud Browser Isolation Search Mechanism

---

CHANGELOG.md
docs/guides/release-notes.md
zpa/services/common/common.go
zpa/services/inspectioncontrol/inspection_custom_controls/zpa_inspection_custom_controls.go
zpa/services/inspectioncontrol/inspection_predefined_controls/zpa_inspection_predefined_controls.go
zpa/services/inspectioncontrol/inspection_profile/zpa_inspection_profile.go
zpa/services/inspectioncontrol/inspection_profile/zpa_inspection_profile_test.go

Fix: Fixed ZPA App Protection resources

---

.github/workflows/zia-test.yml
CHANGELOG.md
docs/guides/release-notes.md
zia/client.go
zia/services/cloudappcontrol/cloudappcontrol.go
zia/services/cloudappcontrol/cloudappcontrol_test.go
zia/services/common/common.go
zia/services/dlp/dlpdictionaries/dlpdictionaries.go
zia/services/dlp/dlpdictionaries/dlpdictionaries_test.go
zia/services/urlcategories/url_categories_test.go
zia/services/urlcategories/urlcategories.go
zia/services/urlfilteringpolicies/urlfilteringpolicies.go
zia/sweep/main_test.go

feat: Added new ZIA Cloud App Control Rule and URL Domain Review Endpoints

---

CHANGELOG.md
docs/guides/release-notes.md
zia/client.go
zia/services/cloudappcontrol/cloudappcontrol.go
zia/services/cloudappcontrol/cloudappcontrol_test.go
zia/services/location/locationmanagement/locationmanagement.go
zia/services/trafficforwarding/vpncredentials/vpncredentials.go

feat: Added Location, VPN credential bulk delete and rule type mapping

---

CHANGELOG.md
docs/guides/release-notes.md
zia/services/location/locationmanagement/locationmanagement.go
zpa/services/segmentgroup/zpa_segment_group.go
zpa/services/segmentgroup/zpa_segment_group_test.go

feat: Added new ZPA PUT v2 Endpoint for Segment Group Updates

---

CHANGELOG.md
docs/guides/release-notes.md
zia/services/trafficforwarding/virtualipaddress/virtualipaddress.go
zia/services/trafficforwarding/virtualipaddress/virtualipaddress_test.go

fix: Added new ZIA GetVIPRecommendedList function

---

CHANGELOG.md
docs/guides/release-notes.md
go.mod
go.sum
zpa/services/policysetcontrollerv2/policysetcontrollerv2.go

Removed `omitempty` from ZPA `microtenant_id` attribute in `policysetcontrollerv2`.

---

CHANGELOG.md
docs/guides/release-notes.md
tests/unit/zpa/zpa_server_group_unit_test.go
zia/services/forwarding_control_policy/zpa_gateways/zpa_gateways_test.go
zpa/services/appconnectorcontroller/zpa_app_connector_controller.go
zpa/services/appconnectorgroup/zpa_app_connector_group.go
zpa/services/applicationsegment/zpa_application_segment.go
zpa/services/applicationsegment_move/applicationsegment_move_test.go
zpa/services/applicationsegment_share/applicationsegment_share_test.go
zpa/services/applicationsegmentbytype/applicationsegmentbytype.go
zpa/services/applicationsegmentbytype/applicationsegmentbytype_test.go
zpa/services/applicationsegmentinspection/zpa_application_segment_inspection.go
zpa/services/applicationsegmentpra/zpa_application_segment_pra.go
zpa/services/browseraccess/zpa_browser_access.go
zpa/services/policysetcontroller/policysetcontroller.go
zpa/services/policysetcontroller/zpa_policy_access_forwarding_rule_test.go
zpa/services/policysetcontroller/zpa_policy_access_inspection_rule_test.go
zpa/services/policysetcontroller/zpa_policy_access_isolation_rule_test.go
zpa/services/policysetcontroller/zpa_policy_access_redirection_rule_test.go
zpa/services/policysetcontroller/zpa_policy_access_rule_test.go
zpa/services/policysetcontroller/zpa_policy_access_timeout_rule_test.go
zpa/services/policysetcontrollerv2/policysetcontrollerv2.go
zpa/services/policysetcontrollerv2/zpa_policy_access_inspection_rule_v2_test.go
zpa/services/policysetcontrollerv2/zpa_policy_access_isolation_rule_v2_test.go
zpa/services/policysetcontrollerv2/zpa_policy_access_redirection_rule_v2_test.go
zpa/services/policysetcontrollerv2/zpa_policy_access_rule_v2_test.go
zpa/services/policysetcontrollerv2/zpa_policy_access_timeout_rule_v2_test.go
zpa/services/servergroup/zpa_server_group.go
zpa/services/servergroup/zpa_server_group_test.go

fix: Enhanced Common SDK Structs

---

CHANGELOG.md
docs/guides/release-notes.md
zpa/services/appconnectorgroup/zpa_app_connector_group.go
zpa/services/applicationsegment/zpa_application_segment.go
zpa/services/applicationsegmentpra/zpa_application_segment_pra.go
zpa/services/policysetcontroller/policysetcontroller.go
zpa/services/policysetcontrollerv2/policysetcontrollerv2.go

fix: Added new App Connector and App Segment Attributes

---

CHANGELOG.md
docs/guides/release-notes.md
zcon/services/common/common.go
zcon/services/provisioning/provisioningurl/provisioningurl.go
zia/client.go
zia/services/pacfiles/pacfiles.go
zia/services/pacfiles/pacfiles_test.go

feat: Added ZIA PAC File and ZCON Provisioning URL Endpoints

---

CHANGELOG.md
zpa/services/applicationsegment/zpa_application_segment.go
zpa/services/applicationsegmentbrowseraccess/application_segment_browser_access.go
zpa/services/applicationsegmentbrowseraccess/application_segment_browser_access_test.go
zpa/services/applicationsegmentinspection/zpa_application_segment_inspection.go
zpa/services/applicationsegmentinspection/zpa_application_segment_inspection_test.go
zpa/services/applicationsegmentpra/zpa_application_segment_pra.go
zpa/services/applicationsegmentpra/zpa_application_segment_pra_test.go

Fix: Fixed ZPA Specialized Application Segments Update Functions

---

CHANGELOG.md
docs/guides/release-notes.md

fix: Fixed ZPA Double Encoding of HTTP GET Request Params

---

.github/workflows/zia-test.yml
.github/workflows/zpa-test.yml
CHANGELOG.md
docs/guides/release-notes.md
zscaler/zia/activation_cli/ziaActivator.go
zscaler/zia/services/firewallpolicies/ipdestinationgroups/ipdestinationgroups_test.go
zscaler/zia/services/sslinspection/sslinspection.go
zscaler/zia/services/sslinspection/sslinspection_test.go
zscaler/zpa/services/appconnectorschedule/appconnectorschedule_test.go
zscaler/zpa/services/privilegedremoteaccess/praapproval/praapproval_test.go
zscaler/zpa/services/serviceedgeschedule/serviceedgeschedule_test.go
zscaler/zpa/sweep/main_test.go

feat: Added ZIA SSL Inspection Rules Endpoint

---

CHANGELOG.md
docs/guides/release-notes.md
zscaler/zia/services/sslinspection/sslinspection.go

fix: Fixed ZIA SSL Inspection Proxy Gateway Attribute

---

.github/workflows/zia-test.yml
.github/workflows/zpa-test.yml
CHANGELOG.md
docs/guides/release-notes.md
zscaler/oneapiclient.go
zscaler/zcc/v2_config.go
zscaler/zcon/v2_config.go
zscaler/zdx/v2_config.go
zscaler/zia/v2_config.go
zscaler/zpa/v2_config.go
zscaler/zwa/v2_config.go

fix Prevent RateLimit client override panic

---

CHANGELOG.md
docs/guides/release-notes.md
zscaler/zia/services/sslinspection/sslinspection.go

fix: Fixed ZIA  validation options

---

CHANGELOG.md
docs/guides/release-notes.md
zscaler/zia/services/devicegroups/devicegroups.go

fix: Fixed ZIA Device Management Pagination

---

CHANGELOG.md
docs/guides/release-notes.md
go.mod
go.sum
zscaler/zpa/services/customerversionprofile/zpa_customer_version_profile.go

fix: Fixed ZPA Custom Version Profiles

---

CHANGELOG.md
docs/guides/release-notes.md
zscaler/zpa/services/common/common.go

fix: Fixed ZPA URL Encoding

---

CHANGELOG.md
docs/guides/release-notes.md
zscaler/zpa/services/common/common.go

fix: Fixed ZPA URL Enconding and ZCC API Client

---

CHANGELOG.md
docs/guides/release-notes.md
zscaler/oneapiclient.go
zscaler/oneapiconfig.go
zscaler/zpa/services/policysetcontrollerv2/policysetcontrollerv2.go
zscaler/zpa/services/serviceedgecontroller/zpa_service_edge_controller.go

fix: Fixed zpa_service_edge_controller mismatched attribute type

---

CHANGELOG.md
docs/guides/release-notes.md
zscaler/zia/services/adminuserrolemgmt/roles/adminroles.go

fix: Fixed ZIA Admin Roles Endpoint

---

CHANGELOG.md
README.md
docs/guides/release-notes.md
zscaler/oneapiclient.go
zscaler/oneapiconfig.go

fix: Fixed OneAPI getRetryAfter function / Proactive Throatling

---

.github/workflows/zcon-test.yml
.github/workflows/zdx-test.yml
.github/workflows/zia-test.yml
.github/workflows/zpa-test.yml
CHANGELOG.md
docs/guides/release-notes.md
zdxcoverage.html
zscaler/zdx/services/reports/devices/device_quality_metrics_test.go
zscaler/zdx/v2_client.go
zscaler/zdx/v2_config.go
zscaler/zpa/services/policysetcontrollerv2/policysetcontrollerv2.go
zscaler/zpa/services/privilegedremoteaccess/pracredentialpool/pracredentialpool.go

fix: Fixed PRA ZPA Resource Attributes

---

CHANGELOG.md
docs/guides/release-notes.md
zscaler/service.go
zscaler/zia/services/common/common.go

fix: Fixed ZIA parameter values  and  for pagination

---

CHANGELOG.md
docs/guides/release-notes.md
zscaler/zpa/services/applicationsegmentbrowseraccess/application_segment_browser_access.go

fix: Added New Browser access Managed Certificate options

---

CHANGELOG.md
docs/guides/release-notes.md
zscaler/oneapiclient.go
zscaler/oneapiconfig.go
zscaler/zpa/services/common/common.go

fix: Fixed OneAPI Retry and Token Renewal Logic

---

CHANGELOG.md
docs/guides/release-notes.md
zscaler/oneapiclient.go
zscaler/oneapiconfig.go
zscaler/zia/services/urlcategories/url_categories_test.go
zscaler/zia/services/urlcategories/urlcategories.go
zscaler/zia/sweep/main_test.go

fix: Fixed ZIA URL Category GetAll

---

CHANGELOG.md
docs/guides/release-notes.md
zscaler/zia/services/urlcategories/urlcategories.go

fix: Added function GetAllCustomURLCategories to ZIA Url Categories package

---

CHANGELOG.md
docs/guides/release-notes.md
go.mod
go.sum
zscaler/zia/services/c2c_incident_receiver/c2c_incident_receiver.go

Fixed ZIA C2C Incident Receiver Struct Type

---

.github/workflows/release.yml
.github/workflows/zia-test.yml
.github/workflows/zidentity.yml
.github/workflows/zpa-test.yml
CHANGELOG.md
docs/guides/release-notes.md
go.mod
go.sum
zscaler/zia/services/dlp/dlpdictionaries/dlpdictionaries.go
zscaler/zia/services/saas_security_api/saas_security_api.go
zscaler/zia/services/vzen_nodes/vzen_nodes.go
zscaler/zia/services/vzen_nodes/vzen_nodes_test.go

feat: Added New ZIA Endpoints and Upgraded to GO v1.24

---

CHANGELOG.md
docs/guides/release-notes.md
go.mod
go.sum
zscaler/ztw/services/activation/activation.go
zscaler/ztw/services/common/common.go
zscaler/ztw/services/ecgroup/ecgroup.go
zscaler/ztw/services/forwarding_gateways/forwarding_gateways.go
zscaler/ztw/services/locationmanagement/location/location.go
zscaler/ztw/services/locationmanagement/locationtemplate/locationtemplates.go
zscaler/ztw/services/policymanagement/forwardingrules/forwardingrules.go
zscaler/ztw/services/policyresources/ipgroups/ipgroups.go
zscaler/ztw/services/policyresources/ipsourcegroups/ipsourcegroups.go
zscaler/ztw/services/policyresources/ipsourcegroups/ipsourcegroups_test.go
zscaler/ztw/services/policyresources/zparesources/zparesources.go
zscaler/ztw/services/provisioning/provisioning_url/provisioning_url.go

fix: Implemented fixes and enhancements to ZTW API endpoint packages

---

CHANGELOG.md
docs/guides/release-notes.md
zscaler/zia/services/advancedthreatsettings/advancedthreatsettings_test.go
zscaler/ztw/services/forwarding_gateways/dns_forwarding_gateway/dns_forwarding_gateway.go
zscaler/ztw/services/forwarding_gateways/zia_forwarding_gateway/zia_forwarding_gateway.go
zscaler/ztw/services/policy_management/forwarding_rules/forwarding_rules.go
zscaler/ztw/services/policy_management/traffic_dns_rules/traffic_dns_rules.go
zscaler/ztw/services/policy_management/traffic_log_rules/traffic_log_rules.go

feat: Added New ZTW Endpoints
